### ISSUE TITLE
Provisioning issues with 1.5.2

### ISSUE THREAD

**Issue by odlevakp** [chef/knife-azure#257] opened 2015-11-10 09:55 UTC
Hello,

when provisioning a new VM and joining it to an existing cloud service I get following error (with -VV):

```xml
.DEBUG: <?xml version="1.0"?>
<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
  <Code>InvalidXmlRequest</Code>
  <Message>The request body's XML was invalid or not correctly specified.</Message>
</Error>

DEBUG: InvalidXmlRequest : The request body's XML was invalid or not correctly specified.
DEBUG: <?xml version="1.0"?>
<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
  <Code>InvalidXmlRequest</Code>
  <Message>The request body's XML was invalid or not correctly specified.</Message>
</Error>

FATAL: Unable to create role:InvalidXmlRequest : The request body's XML was invalid or not correctly specified.
ERROR: Failed to create the server -- exception being rescued: exception class/object expected
DEBUG: TypeError: exception class/object expected
/home/vagrant/.chefdk/gem/ruby/2.1.0/gems/knife-azure-1.5.2/lib/azure/deploy.rb:103:in `raise'
/home/vagrant/.chefdk/gem/ruby/2.1.0/gems/knife-azure-1.5.2/lib/azure/deploy.rb:103:in `create'
/home/vagrant/.chefdk/gem/ruby/2.1.0/gems/knife-azure-1.5.2/lib/chef/knife/azure_server_create.rb:631:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:405:in `block in run_with_pretty_exceptions'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:404:in `run_with_pretty_exceptions'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:203:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/knife.rb:142:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/knife:25:in `<top (required)>'
/opt/chefdk/bin/knife:54:in `load'
/opt/chefdk/bin/knife:54:in `<main>'

```

It was happening on my local machine, did a clean install on a vagrant `Ubuntu 14.04 LTS` box with the same result, as you can see above.

I was able to fix it by installing the 1.4.0 version, where the same server create commands works.

```bash
vagrant@vagrant:~$ gem uninstall knife-azure
Successfully uninstalled knife-azure-1.5.2

vagrant@vagrant:~$ gem install knife-azure -v 1.4.0 
Fetching: knife-azure-1.4.0.gem (100%)
Successfully installed knife-azure-1.4.0
```

Maybe I am just not aware of some configuration changes in the latest version and this is an expected behaviour.

**Comment by Aliasgar16** [comment] 2015-11-16 04:37
@odlevakp can you share the knife-azure command through which you are trying to create the VM under an existing cloud service ?

**Comment by adamedx** [comment] 2015-11-16 17:08
This may be an instance of https://github.com/chef/knife-azure/issues/249.

**Comment by odlevakp** [comment] 2015-11-20 14:45
Yes, seems it's a duplicate of #249 - didn't spot that one before.

**Comment by adamedx** [comment] 2015-11-25 06:26
Closing as a duplicate of #249.

**Closed by adamedx** 2015-11-25 06:26 UTC
