### ISSUE TITLE
Knife Azure Creating a new server

### ISSUE THREAD

**Issue by shridevops15** [chef/knife-azure#343] opened 2016-04-20 22:20 UTC
I have tried using the below command to create a new server using my custom image. I have included all the parameters. I have used the DNS Server name  and storage account provided by my systems admin. 

[root@infcchfwtnd01 chef-repo]#  knife azure server create --azure-vm-name azuredev06 --azure-subscription-id '42a288f8-3bf2-47a8-9a41-11' --azure-vm-size Medium --azure-source-image ecint-std-centos67-v01 --azure-dns-name  csdigplc.cloudapp.net --azure-network-name nwc-ecint --azure-service-location 'Central US' --azure-storage-account saclrsdiglcdev01 --azure-subnet-name nwc-ecint-dev --ssh-user chefadmin --ssh-password '*****'

...WARN: BadRequest : The hosted service name is invalid.
WARN: Unable to find hosted(cloud) service:BadRequest : The hosted service name is invalid.
...WARN: BadRequest : The hosted service name is invalid.
FATAL: Unable to create DNS:BadRequest : The hosted service name is invalid.
ERROR: Failed to create the server -- exception being rescued: exit
WARNING: Cleaning up resources...
.WARN: BadRequest : The hosted service name is invalid.
WARN: Unable to find hosted(cloud) service:BadRequest : The hosted service name is invalid.
ERROR: knife encountered an unexpected error
This may be a bug in the 'azure server create' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `content' for nil:NilClass

**Comment by NimishaS** [comment] 2016-05-10 07:18
@shridevops15 , this looks like duplicate of https://github.com/chef/knife-azure/issues/342.
Closing this one. We'll work on https://github.com/chef/knife-azure/issues/342. Please feel free to re-open if we miss out on anything.

**Closed by NimishaS** 2016-05-10 07:18 UTC

**Comment by dheerajd-msys** [comment] 2016-05-10 13:35
@shridevops15,

According to the capture process for Linux VMs, all Linux images must be deprovisioned by running the waagent command with the -deprovision option. Then you can choose "I have run waagent-deprovision on the virtual machine" to indicate that the operating system is prepared to be an image.

I followed the steps and was able to create the VM with created Image. 
Please run command `waagent -deprovision` in the VM which you want to get imaged.

Now during image creation you need to select the option "I have run waagent-deprovision on the virtual machine" and complete.

Thanks
