### ISSUE TITLE
knife-azure does not work with latest Chefdk

### ISSUE THREAD

**Issue by enrigh0338** [chef/knife-azure#440] opened 2017-07-17 13:53 UTC
knife-azure does not work with latest chefdk (2.0.28). gem collision error

![image](https://user-images.githubusercontent.com/30216910/28271120-bbdac57a-6ad5-11e7-8c38-8137e5ee364b.png)

**Comment by rahulkumardbit** [comment] 2017-07-18 06:49
Hi, 
I had same issue with latest version when installing on windows. There is some issue with ruby 2.4. So I installed v1.5.0 with 2.3.0 which is working fine.

**Comment by enrigh0338** [comment] 2017-07-18 13:51
I did the same

**Comment by gazataeon** [comment] 2017-07-18 22:00
same here:

:/opscode/chefdk/embedded/lib/ruby/2.4.0/rubygems/specification.rb:2291:in `raise_if_conflicts': Unable to activate knife-azure-1.7.0, because listen-3.1.5 conflicts with listen (= 3.0.6) (Gem::ConflictError)

**Comment by btm** [comment] 2017-07-24 15:06
Fix is being worked on here: https://github.com/chef/knife-azure/pull/445

**Comment by Babu2000** [comment] 2017-09-20 14:49
Still issues is reproducible with latest chefdk and knife-azure 1.7.0. Any updates on this issue.

**Comment by NimishaS** [comment] 2017-09-28 12:50
Fixed in `knife-azure 1.8.0`.

**Closed by NimishaS** 2017-09-28 12:50 UTC
