### ISSUE TITLE
Error creating a VNET

### ISSUE THREAD

**Issue by vkurpad** [chef/knife-azure#178] opened 2015-01-05 18:45 UTC
I'm trying to create a VNET with the command 
knife azure vnet create -n 'ChefDemoVNET' -a 'ChefDemoAG' --azure-address-space '10.0.0.0/24'
where ChefDemoAG is an existing ag. 

Error out with the message:
.ERROR: knife encountered an unexpected error
This may be a bug in the 'azure vnet create' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a
bug report.
Exception: NoMethodError: undefined method `add_next_sibling' for nil:NilClass

**Comment by jeffmendoza** [comment] 2015-01-05 18:55
Yes, this is a bug when you don't already have an existing vnet. The code should be able to handle this case, but it doesn't =(

**Comment by siddheshwar-more** [comment] 2015-01-06 07:49
@vkurpad We are looking into this!

**Comment by siddheshwar-more** [comment] 2015-01-06 16:30
@vkurpad 
Here is fix - https://github.com/opscode/knife-azure/pull/179

I think currently `knife azure vnet create` only updates existing vnet. Seems it doesn't supports creation of new vnet!

**Comment by siddheshwar-more** [comment] 2015-01-09 02:19
@jeffmendoza 

We found following things related to `knife azure vnet create` command :
1. This command only can update existing VNet. We can't create new one using this.
2. Azure Rest api supports **Get**, **Set** and **List** operation on VNet.
   I think Azure api don't support creation of new VNet.
   Ref-  http://msdn.microsoft.com/en-us/library/azure/jj157182.aspx 

3. And this issue is because @vkurpad is trying to update non existing VNet. 

**Conclusion-** 
By considering above points i think we should rename `knife azure vnet create` to `knife azure vnet update`. And also update README with proper details.

**Comment by jeffmendoza** [comment] 2015-01-09 21:40
So, there are no create/delete commands, just a get config and set config command:
http://msdn.microsoft.com/en-us/library/azure/jj157196.aspx
http://msdn.microsoft.com/en-us/library/azure/jj157181.aspx

The config can contain multiple vnets. The current vnet create command gets the config, and tries to add a new vnet to the list in the xml. Something like:

```
<config>
<vnets>
  <vnet />
  <vnet />
</vnets>
</config>
```

The code will look for the tag where the vents are and add a new one. This works if you already have at least one existing vnet.

The problem is when you have no existing vnets, the config looks like:

```
<config />
```

This is where the code chokes.

https://github.com/opscode/knife-azure/blob/master/lib/azure/vnet.rb#L75
```
      vnets = response.css('VirtualNetworkSite')
      vnets.each { |vn| vnet = vn if vn['name'] == params[:azure_vnet_name] }
```
`VirtualNetworkSite` is not found, so the `.each` does not work.

**Comment by siddheshwar-more** [comment] 2015-01-13 13:29
@jeffmendoza 
Could you please review #179

**Comment by adamedx** [comment] 2015-02-09 23:26
This was resolved with https://github.com/chef/knife-azure/pull/179. Thank you for your report @vkurpad.

**Closed** 2015-02-09 23:26 UTC
