### ISSUE TITLE
"knife azurerm server create" complains that a non-existent node exists

### ISSUE THREAD

**Issue by rodriguesalex** [chef/knife-azure#441] opened 2017-07-18 01:24 UTC
Chef Development Kit Version: 1.5.0
chef-client version: 12.21.2

When using "knife azurerm server create", I am presented with the following message even though the node does not exist and has never existed:
"Node  exists, overwrite it? (Y/N)"

If I answer "Y", the following error is thrown
ERROR: 405 "Method Not Allowed"
ERROR: Something went wrong. Please use -VV option for more details.

An extract of the debug (-VV) output is below:
```
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 405 Method Not Allowed
DEBUG: allow: GET, POST
DEBUG: content-type: text/html
DEBUG: date: Tue, 18 Jul 2017 01:15:27 GMT
DEBUG: server: openresty/1.11.2.1
DEBUG: x-ops-api-info: flavor=cs;version=12.0.0;oc_erchef=12.15.8+20170629175019
DEBUG: x-ops-server-api-version: {"min_version":"0","max_version":"1","request_version":"1","response_version":"1"}
DEBUG: content-length: 177
DEBUG: connection: Close
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: ---- HTTP Response Body ----
DEBUG: <html><head><title>405 Method Not Allowed</title></head><body><h1>Method Not Allowed</h1>Method Not Allowed<p><hr><address>mochiweb+webmachine web server</address></body></html>
DEBUG: ---- End HTTP Response Body -----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: Content-Length validated correctly.
DEBUG: Chef::HTTP calling Chef::HTTP::APIVersions#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Expected JSON response, but got content-type 'text/html'
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
INFO: HTTP Request Returned 405 Method Not Allowed:
ERROR: 405 "Method Not Allowed"
ERROR: Something went wrong. Please use -VV option for more details.
DEBUG: C:/opscode/chefdk/embedded/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2-universal-mingw32/lib/chef/http.rb:150:in `request'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2-universal-mingw32/lib/chef/http.rb:139:in `delete'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2-universal-mingw32/lib/chef/knife/bootstrap/client_builder.rb:175:in `sanity_check'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2-universal-mingw32/lib/chef/knife/bootstrap/client_builder.rb:52:in `run'
C:/Users/arodrigues/AppData/Local/chefdk/gem/ruby/2.3.0/gems/knife-azure-1.7.0/lib/chef/knife/bootstrap/bootstrapper.rb:337:in `get_chef_extension_private_params'
C:/Users/arodrigues/AppData/Local/chefdk/gem/ruby/2.3.0/gems/knife-azure-1.7.0/lib/chef/knife/azurerm_server_create.rb:250:in `create_server_def'
C:/Users/arodrigues/AppData/Local/chefdk/gem/ruby/2.3.0/gems/knife-azure-1.7.0/lib/chef/knife/azurerm_server_create.rb:201:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2-universal-mingw32/lib/chef/knife.rb:443:in `block in run_with_pretty_exceptions'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2-universal-mingw32/lib/chef/knife.rb:442:in `run_with_pretty_exceptions'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2-universal-mingw32/lib/chef/knife.rb:219:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2-universal-mingw32/lib/chef/application/knife.rb:156:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2-universal-mingw32/bin/knife:25:in `<top (required)>'
C:/opscode/chefdk/bin/knife:68:in `load'
C:/opscode/chefdk/bin/knife:68:in `<main>'
```

**Comment by gazataeon** [comment] 2017-07-21 09:05
This is really odd. I seem to be getting this recently now too. I physically can't deploy any Azure VMs this way. I can't say for sure but it seems to be since the DK 2.0 update, but a downgrade doesn't seem to fix it either.
Using the hosted Chef manage platform.

> `DEBUG: ---- End HTTP Response Body -----
Node  exists, overwrite it? (Y/N) y

DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: Content-Length validated correctly.
DEBUG: Chef::HTTP calling Chef::HTTP::APIVersions#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Expected JSON response, but got content-type 'text/html'
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
INFO: HTTP Request Returned 405 Method Not Allowed:
ERROR: 405 "Method Not Allowed"
`

**Comment by enrigh0338** [comment] 2017-07-24 16:08
as a workaround you can give the node_name specifically using the -N flag. What seems to be happening is Chef finds a node named "" (empty string) and thinks it's actually a node or at least it errors like it is.

**Comment by NAshwini** [comment] 2017-07-26 14:27
Hi @rodriguesalex,
 
I tried to reproduce the issue with latest gems `knife-azure (1.7.0)`, & with various chefdk vesion such as
```
Chef Development Kit Version: 1.5.0
chef-client version: 13.2.20
```
and 
```
Chef Development Kit Version: 1.3.8
chef-client version: 12.19.36
```
Also tried with `chef-client version 13.2.20`.

-- But I am unable to reproduce this issue. For me the below commands of windows & ubuntu vm worked successfully.
**For Ubuntu**:
```
bundle exec knife azurerm server create --azure-resource-group-name ashResourceGrp15 --azure-vm-name ashubuntu --azure-service-location 'westus' --azure-image-os-type ubuntu --azure-image-reference-sku '14.04.2-LTS' -x azureuser --ssh-password azureAzure@123 --azure-vm-size Small -r "recipe[cbk1]" -c D:\chef-repo\.chef\knife.rb -N ashubuntu
```
**For Windows**:
```
bundle exec knife azurerm server create  --azure-resource-group-name AshResourceGrpName  --azure-vm-name ashu-win --azure-service-location 'westus'  --azure-image-os-type windows  -x azure -P azure@123456 -c D:\chef-repo\.chef\knife.rb -VV
```

-- It would be helpful if you can share all the steps to reproduce the issue.


Thanks and Regards,
Ashwini

**Comment by NAshwini** [comment] 2017-08-01 13:48
Hi @rodriguesalex, 
Please share your "knife azurerm server create" command and knife.rb file.

**Comment by NimishaS** [comment] 2017-08-21 07:01
@rodriguesalex , any updates on this?

**Comment by NimishaS** [comment] 2017-09-28 12:58
Sorry we weren't able to reproduce your issue. If you're still experiencing this issue please provide additional information and we'll be happy to help again.
Please check with the latest `knife-azure 1.8.0`.

**Comment by RickFlist** [comment] 2018-03-27 19:28
Hi folks,

I am able to repro this issue. I am using whatever the latest version of the gem and Chef DK since I just set this up a couple days ago (I don't know how to make it echo version numbers).

I get "Method Not Allowed" when I execute the following Knife command:
`knife azure server create --azure-dns-name 'mrsrvr04' --azure-vm-name 'MISRVR04' --azure-vm-size 'Small' --azure-storage-account 'cheftestvhds' --bootstrap-protocol 'cloud-api' --azure-source-image 'fb83b3509582419d99629ce476bcb5c8__SQL16_SP1_QFE-CU13.0.4435.0SQLSTDWindowsServer20161' --azure-service-location 'westus' --winrm-user miadmin --winrm-password '@dm1nP@ssw0rd!' --tcp-endpoints 80,3389,5985,5984 --r 'recipe[webserver]'`

The error immediately goes away if I use this command:
`knife azure server create --azure-dns-name 'mrsrvr04' --azure-vm-name 'MISRVR04' --azure-vm-size 'Small' --azure-storage-account 'cheftestvhds' --bootstrap-protocol 'cloud-api' --azure-source-image 'fb83b3509582419d99629ce476bcb5c8__SQL16_SP1_QFE-CU13.0.4435.0SQLSTDWindowsServer20161' --azure-service-location 'westus' --winrm-user miadmin --winrm-password '@dm1nP@ssw0rd!' --tcp-endpoints 80,3389,5985,5984 --r 'recipe[webserver]' -N 'MISRVR04'`

Knife.rb
[knife.rb.txt](https://github.com/chef/knife-azure/files/1853482/knife.rb.txt)

**Comment by piyushawasthi** [comment] 2018-04-16 12:17
Hi @RickFlist Thanks for your help.

**Comment by piyushawasthi** [comment] 2018-04-16 12:17
@rodriguesalex this issue fixed in PR: https://github.com/chef/knife-azure/pull/472

**Closed** 2018-05-30 07:36 UTC
