### ISSUE TITLE
"knife azurerm server create" creates node but fails to register it with chef server.

### ISSUE THREAD

**Issue by Dalaigh88** [chef/knife-azure#409] opened 2016-11-04 15:38 UTC
Trying to create a server via knife-azure. Server is created correctly but doesn't seem to bootstrap or to register with chef server. Running "knife bootstrap azurerm"  gives error:

"Creating VirtualMachineExtension....
ERROR: Virtual machine <nodename> already has Chef extension installed on it."

Running "knife bootstrap" with DNS address correctly bootstraps and registers node.

**Comment by Vasu1105** [comment] 2016-11-14 07:23
Please add details about how you are creating VM is it from portal or by using knife azurerm server create command. Also add detailed logs using -VV option.

**Comment by NimishaS** [comment] 2017-02-17 06:20
@Dalaigh88 , any updates on this?

**Comment by NimishaS** [comment] 2017-03-22 07:06
@Dalaigh88 , one more possibility can be that the recipe you are passing in the runlist is not working successfully.
I am closing this issue as we are not able to reproduce it and there isn't any response on this issue for a long time.

**Closed by NimishaS** 2017-03-22 07:06 UTC

**Comment by dheerajd-msys** [comment] 2017-03-23 12:22
I have also verified and unable to reproduce the issue. Node registered successfully on Chef-server and all parameters are being set viz. FQDN, IP Address, and Platform etc. There could be possibility that runlist you are passing is faulty.

**Comment by mangesh1983** [comment] 2017-07-15 19:13
Hi Team,

I am getting similar kind of issue, VM deployment success but running was not executed.
I also node not register in chef , show unknown status.

Please find the attached file will details ,please let me know you suggestion on this where I went wrong.
I have check recipes are working , if I manually bootstrap Node and run .
[Chef_bootstarp issue for azureVM.docx](https://github.com/chef/knife-azure/files/1150566/Chef_bootstarp.issue.for.azureVM.docx)

**Comment by NimishaS** [comment] 2017-07-25 09:21
Hi @mangesh1983 , your issue is being worked on. 
This issue is occurring as chef-client is taking more than 5 minutes to download and install, which is resulting into extension timeout. We are looking at why the MSI is taking more time now. Previously it used to take 2-3 minutes.

**Comment by mangesh1983** [comment] 2017-07-25 10:10
Hi Nimisha,

Thanks for looking into it,

Just to update you issue has been resolved now, I found validation key
parameter is need to mention in knife.rb file for azure environment  (if we
are using knife tool) to install chef client and register to Chef server,
however validation authentication method is old for register node into chef
server but is required for azure.

Thanks
Mangesh kharade

**Comment by NimishaS** [comment] 2017-07-25 10:26
Thanks for update @mangesh1983 . Yes `knife azurerm` commands require `validation_key` as it uses the `azure-chef-extension` for bootstrapping the node and `azure-chef-extension` needs `validation_key`.

**Comment by NimishaS** [comment] 2017-07-25 10:34
@mangesh1983 , can you please confirm if you have created an issue with Chef with title `Need help to deploy VM in Microsoft Azure using chef-automation`?

**Comment by mangesh1983** [comment] 2017-07-25 10:54
Yes right, I did, one more issue I observed  knife azurerm commands to work
with ChefDK 13.0 or latest version, It is only work with chefDk 1.5 or
lower version.

I think need to do some modification in knife azurerm plugin for this
reason I keep that ticket open, if need you can close that ticket.

Thanks
Mangesh kharade

**Comment by mangesh1983** [comment] 2017-07-25 10:54
Yes right, I did, one more issue I observed  knife azurerm commands are not
working with ChefDK 13.0 or latest version, It is only work with chefDk 1.5
or lower version.

I think need to do some modification in knife azurerm plugin for this
reason I keep that ticket open, if need you can close that ticket.

Thanks

**Comment by NimishaS** [comment] 2017-07-25 10:58
The latest `chef-dk` related issue is being addressed here: https://github.com/chef/knife-azure/pull/445
