### ISSUE TITLE
knife-azure does not work with latest chefdk (2.3.1). gem collision error

### ISSUE THREAD

**Issue by Babu2000** [chef/knife-azure#461] opened 2017-09-20 20:09 UTC
C:/opscode/chefdk/embedded/lib/ruby/2.4.0/rubygems/specification.rb:2293:in `raise_if_conflicts': Unable to activate knife-azure-1.7.0, because listen-3.1.5 conflicts with listen (= 3.0.6) (Gem::ConflictError)
        from C:/opscode/chefdk/embedded/lib/ruby/2.4.0/rubygems/specification.rb:1413:in `activate'
        from C:/opscode/chefdk/embedded/lib/ruby/2.4.0/rubygems.rb:220:in `rescue in try_activate'
        from C:/opscode/chefdk/embedded/lib/ruby/2.4.0/rubygems.rb:213:in `try_activate'
        from C:/opscode/chefdk/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
        from C:/opscode/chefdk/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from C:/Users/chefwsmodeler/AppData/Local/chefdk/gem/ruby/2.4.0/gems/knife-azure-1.7.0/lib/chef/knife/azurerm_ba
se.rb:21:in `<top (required)>'

**Comment by NimishaS** [comment] 2017-09-21 07:58
@Babu2000 , this issue has been resolved but `knife-azure` isn't released yet. We'll be releasing it shortly.
I am closing this issue since it's a duplicate of https://github.com/chef/knife-azure/issues/440.

**Closed** 2017-09-21 07:58 UTC
Labels: duplicate
