### ISSUE TITLE
Unable to execute chef cookbooks in azure RM VM

### ISSUE THREAD

**Issue by naveenkt59** [chef/knife-azure#465] opened 2017-12-28 12:09 UTC
I am trying to create azure RM vm using the knife commands given here https://github.com/chef/knife-azure/blob/master/docs/ARM.md. When providing the chef cookbooks in the command,the VM is created but chef cookbooks are not getting executed and there is no error getting displayed as well..it just shows "Creating virtual machine" but after few minutes, process gets over .The node is getting bootstrapped and is visible in the chef server as well..Does anyone know why the chef cookbooks are not getting executed and how to resolve the issue?
Thanks

**Comment by dheerajd-msys** [comment] 2018-02-20 13:43
@naveenkt59, Thanks for pointing this issue. I have verified it too from my side and issue is reproduced.
I've used below command to reproduce the issue:
```
bundle exec knife azurerm server create  --azure-resource-group-name dhdevelopment2 --azure-vm-name dhwinarm2 --azure-service-location 'eastus'  --azure-image-os-type windows  -x azureuser -P azure@123456 --azure-vnet-name default-vnet --azure-vnet-subnet-name default_subnet -c D:\chef-starter\chef-repo\.chef\knife.rb -r recipe[starter]
```
We will dig more into it and get back to you.

**Comment by dheerajd-msys** [comment] 2018-03-12 13:01
@naveenkt59, Figured out the root cause and working on to fix it. For time being you can use `-E _default`  along with your command.
Example:
```
bundle exec knife azurerm server create  --azure-resource-group-name dhdevelopment2 --azure-vm-name dhwinarm2 --azure-service-location 'eastus'  --azure-image-os-type windows  -x azureuser -P azure@123456 --azure-vnet-name default-vnet --azure-vnet-subnet-name default_subnet -c D:\chef-starter\chef-repo\.chef\knife.rb -r recipe[starter] -E _default
```
Thanks.

**Comment by naveenkt59** [comment] 2018-03-15 11:01
Sure ,I will. Thanks

**Comment by Vasu1105** [comment] 2018-04-16 07:54
@naveenkt59 Using -E option is your problem got solved ?

**Comment by dheerajd-msys** [comment] 2018-05-09 09:42
@naveenkt59 did you check your commands and suggestions posted here lately?

**Comment by dheerajd-msys** [comment] 2018-05-14 12:52
@naveenkt59 Could you please verify by running command again with your intact cookbook which is uploaded on chef-server. We've checked it on our side that cookbook is executing properly without any fix required.

We've used below command : 
```
PS D:\Chef_Repo\knife-azure> bundle exec knife azurerm server create -x azure -P azure@123 --azure-image-reference-offer WindowsServer --azure-image-reference-publish
rosoftWindowsServer --azure-image-reference-sku 2012-R2-Datacenter  --azure-service-location 'eastus' --azure-vm-name dhtestvm1 --azure-resource-group-name dh-win1 -c D:\chef-starter\chef-repo\.chef\knife.rb -r "recipe[starter]" -VV
```
You can try with attached cookbook which is simplest to execute.
[starter.zip](https://github.com/chef/knife-azure/files/2000734/starter.zip)

**Comment by Vasu1105** [comment] 2018-05-21 11:09
Closing this since not able to reproduce. @naveenkt59 please provide logs and command that you are executing also cookbook details that you are running.

**Closed by Vasu1105** 2018-05-21 11:09 UTC
