### ISSUE TITLE
knife azure server create - intermittent authorized_keys CERT thumbprint error - v.1.4.0-1.6.0.rc.0

### ISSUE THREAD

**Issue by airborne-donkey** [chef/knife-azure#273] opened 2015-12-16 01:39 UTC
Error message intermittently received during knife-azure deployment - began Wed PM Dec 2nd:
"FATAL: Unable to create role:BadRequest : The certificate with thumbprint ____ was not found"

We can issue the same exact command multiple times - just minutes from each other.  Sometimes error will occur, sometimes command will successfully complete - it seems to be random.  The workaround right now is - if anyone gets this error message, just re-submit same exact command and hope it goes through.  This definitely impacts ability to use knife-azure for reliable end-to-end environmental deployments.

In -VV debug mode, we notice the same thumbprint given in the error message is EXACTLY SAME as what's submitted XML in the "PublicKeys" session for authorized_keys :

```
<PublicKeys>
      <PublicKey>
        <Fingerprint>SAME THUMBPRINT AS ERROR</Fingerprint>
        <Path>/home/devops/.ssh/authorized_keys</Path>
      </PublicKey>
    </PublicKeys>
```

This issue began ~ Wednesday Dec 2nd evening time (PST) - we happened to notice same timeframe the new Azure Portal went GA.  Is it possible something was updated on the Azure API that reduced backwards compatibility with the format these SSH key thumbprints are being submitted by the knife-azure tool?

**Comment by airborne77** [comment] 2015-12-16 01:55
NOTE:  We have attempted this from multiple different Chef workstations & locations - including CentOS 6.7, 7.1 & Ubuntu LTS.  We have also tried this with both knife-azure 1.4.0 and 1.6.0.rc.0. We have tried both using --identity-key parameter, and not using (just --ssh-password)- issue occurring consistently (although intermittently ~50% time).

Here is an example output of two deploys done exactly 8 minutes apart issuing same exact command - first one fails, next command exactly the same works:
 
__________________________________
**** Deploying tdtest3-cr01 ****
 
................FATAL: Unable to create role:BadRequest : The certificate with thumbprint 9752CD8489092C1CADE511E227308BD57AC6A76A was not found.
ERROR: Failed to create the server -- exception being rescued: exception class/object expected
WARNING: Cleaning up resources...

**** Deploying tdtest3-cr01 ****

...............
Waiting for virtual machine to reach status 'provisioning’….
......vm state 'provisioning' reached after 3.91 minutes.
Waiting for virtual machine to reach status 'ready'...
_________________________________________
See attached for full -VV debug output of the failure (with sensitive items removed).
[az-deployment-bad-cert-error.pdf](https://github.com/chef/knife-azure/files/63453/az-deployment-bad-cert-error.pdf)

**Comment by NimishaS** [comment] 2015-12-18 17:09
@airborne77 We tried to reproduce this issue,but couldn't. 
When we ran two commands parallely, that time we faced conflict error:
```
FATAL: Unable to create role:ConflictError : Windows Azure is currently performing an operation on this hosted service that requires exclusive access.

FATAL: Unable to create role:ConflictError : Windows Azure is currently performing an operation with x-ms-requestid 1001abc8cb8053e4b6a4775865645505 on this deployment that requires exclusive access
```
There has been some maintenance work going on in `Azure` which will continue for at least 2 more days. We are also facing some unexpected bugs. This could be the reason for the issue you faced.

**Comment by airborne77** [comment] 2015-12-18 21:43
Thanks for the update NimishaS.  We've also certainly gotten that error.  In our deployment scripts, we previously had "sleep 30" commands between each "knife azure server create", then needed to increase to "sleep 60", now not even "sleep 90" prevents against getting that error.

We still are getting the error intermittently, even yesterday & today, albeit may be happening more like 10% instead of 50% of the time seeing before:
> the certificate with thumbprint <THUMBPRINT> was not found.

Our deployment scripts that deploy end-to-end environments are triggered regularly, so we'll observe behavior after this 2 day Azure maintenance timeframe you mention and report back.

How can we gain greater insight into when Azure is performing this kind of maintenance - especially on the API?

**Comment by nromyn** [comment] 2015-12-18 21:51
@airborne77 The fatal error regarding exclusive access has to do with the Azure Service Model; the Azure Resource Manager model supports concurrent operations, which may remove the requirement for the sleep.

**Comment by airborne77** [comment] 2015-12-18 21:52
Good to know - yes we have not moved to the Resource Manager model yet.  Is there a migration plan for knife-azure towards that newer methodology?

**Comment by airborne77** [comment] 2015-12-22 01:10
FYI - still getting same intermittent CERT errors today.  It does seem to happen in conjunction with concurrent services being deployed into same Cloud Service.

Confirmed from two separate workstations in different locations executing commands to two different Azure subscriptions - both getting intermittent CERT errors.

If we wait until each VM is deployed and bootstrapped before moving to next one, we seem to have no issues.  Strange since it's an ~/.ssh/authorized_keys issue.

**Comment by rfedoriu** [comment] 2016-01-11 21:24
I've been getting the exact same error described by @airborne77 when running 'knife azure server create', seemingly randomly. One time it will work and create a VM successfully, and just minutes after completion of the first operation another run may produce the 'Thumbprint' error several times before a successful run. It seems that this just requires repeating the command until it works. 
Any info on what causes this would be appreciated.
Thanks.

**Comment by airborne77** [comment] 2016-01-14 19:18
Hi all - will knife-azure will be a supported tool going forward?  My organization has experienced the CERT errors (and other issues with concurrency etc) long enough on all known knife-azure versions - including 1.6.0.rc.0, and has created visible delays and blocking issues for us.  We likely soon will change the path we are using for the infrastructure deployments to another tool if we have no updates on this item.

**Comment by adamedx** [comment] 2016-01-19 05:11
@NimishaS, can you confirm this is a consequence of using ASM rather than ARM?

@airborne77 the plugin is absolutely supported, the problem is we can't reproduce the issue and therefore can't debug it. If you're available for a meeting, we could schedule something for you to repro it that would allow us to debug.

**Comment by kpkrishnamoorthy** [comment] 2016-03-29 22:51
If this information is useful, I've temporarily fixed this by adding a 10-second sleep in <gem>/lib/azure/certificate.rb, in the `Azure::Certificate.create` function. Just before the `@fingerprint` statement.

Since I've not yet been able to successfully use knife-azure version 1.5.2 (due to incorrect XML errors), I made this modification in knife-azure version 1.4.0.

**Comment by airborne77** [comment] 2016-03-30 00:23
thanks for the update KP.

We are still curious about the future of this knife-azure plugin, now that azure has moved to the ARM based model, and the tool only seems to support the ASM (classic) model.

For now, although we would have loved to stick with chef tools & plugins, we have moved to using the Azure Linux CLI to facilitate our Azure infrastructure automation, which is much more stable and fully featured.

**Comment by Vasu1105** [comment] 2016-03-30 05:40
@airborne77  We already started working on giving support for ARM in knife plugin it will be release soon.

**Comment by btm** [comment] 2016-11-15 15:48
@NimishaS is there a check we could add to Azure::Certificate#add_certificate after the Azure API call that we could use to query that the certificate is readable and loop a few times until it is?

**Comment by Vasu1105** [comment] 2016-11-17 07:26
@btm yes we can add this after adding certificate and check if certificate available and then proceed for VM creation call.  We are not able to reproduce the issue at our end but this fix can help in fixing the issue.

**Comment by btm** [comment] 2016-11-23 15:23
A check for the certificate was added in https://github.com/chef/knife-azure/pull/413 and will be in the next release.

**Closed by btm** 2016-11-23 15:23 UTC
