### ISSUE TITLE
knife azure does not honor --node-ssl-verify-mode flag

### ISSUE THREAD

**Issue by vinyar** [chef/knife-azure#250] opened 2015-11-02 19:38 UTC
Bug:
When `--node-ssl-verify-mode none` is specified no changes are made to client.rb

Expectation:
ssl_verify_mode :verify_none is rendered to the client.rb

Actual:
no changes are made to the file

Notes:
* --no-node-verify-api-cert does place additional text in the client.rb (does not resolve auth with custom trust auth certificates)
* a custom gem is available for testing (verify now) - adamedx/node_ssl_verify

**Comment by vinyar** [comment] 2015-11-02 19:40
@msnahill for more info

**Comment by vinyar** [comment] 2015-11-02 20:06
No cigar:
Manually built the knife-azure gem from https://github.com/chef/knife-azure/tree/adamedx/node_ssl_verify fork.

Command:
`knife azure server create --azure-dns-name myserver --azure-vm-size Medium -I a699494373c04fc0bc8f2bb1389d6106__Windows-Server-2012-R2-20150916-en.us-127GB.vhd --azure-service-location 'Central US' --winrm-user myuser --winrm-password 'cleartextpassword' --bootstrap-protocol cloud-api --azure-network-name 'vnet_express_route' --azure-subnet-name 'Tenant Subnet' --no-node-verify-api-cert --node-ssl-verify-mode none --azure-vm-startup-timeout 15 
`

Error:
OpenSSL::SSL:SSLError: SSL_Connect refused.

Notes:
* manually adding `ssl_verify_mode :verify_none` solves the issue
other note:
* `knife ssl fetch -c client.rb` fails with uninitialized constant Chef::Handler azure/start_hander, report_handler..

**Comment by vinyar** [comment] 2015-11-02 20:33
bootstrapping a box with new gem placed a literal `knife[:node_ssl_verify_mode] = 'none'`

**Comment by vinyar** [comment] 2015-11-02 20:41
the only way this command works is with exactly `ssl_verify_mode :verify_none`
no `=` and no `knife[:...]`

**Comment by vinyar** [comment] 2015-11-02 20:43
also, unrelated findings:
 `validator_client_name` & `chef_server_url` are defined twice.

/cc: @andrewelizondo

**Comment by siddheshwar-more** [comment] 2015-11-03 06:08
@vinyar @andrewelizondo 
We are working on this. Thank You!

**Comment by NimishaS** [comment] 2015-11-03 12:07
Work in progress: https://github.com/chef/knife-azure/pull/253
https://github.com/chef-partners/azure-chef-extension/pull/87

**Comment by vinyar** [comment] 2015-11-04 22:34
:+1:

**Comment by NimishaS** [comment] 2015-11-06 08:59
@vinyar , we have provided a work-around for this. You can use `--azure-extension-client-config` option in `knife azure server create` command to specify the path of `client.rb` file which contains all the required options. 
Please use `knife-azure` master branch.

**Comment by vinyar** [comment] 2015-11-09 22:45
@NimishaS 
Hi, we'll test it and get back to you.
Q: Will passing node name add the value to client.rb?

Could you please update the readme.md with directions on how to use this flag (so others can benefit from the workaround)

Thank you

**Comment by vinyar** [comment] 2015-11-10 02:04
@NimishaS - No luck. Invalid option.

knife azure server create --azure-dns-name myserver --azure-vm-size Medium -I a699494373c04fc0bc8f2bb1389d6106__Windows-Server-2012-R2-20150916-en.us-127GB.vhd --azure-service-location 'Central US' --winrm-user myuser --winrm-password 'cleartextpassword' --bootstrap-protocol cloud-api --azure-network-name 'vnet_express_route' --azure-subnet-name 'Tenant Subnet' --no-node-verify-api-cert --node-ssl-verify-mode none --azure-vm-startup-timeout 15 --azure-domain-name 'ExpressRoute.domain.example.com' --azure-domain-passwd 'AnotherClearTextPassword' --azure-domain-user 'domainaccount' --azure-domain-ou-dn 'OU=SubFolder,OU=Folder,DC=ExpressRoute,DC=domain,DC=example,DC=com'  --azure-extension-client-config 'D:\myfolder\client.rb'

`Error: invalid option: --azure-extension-client-config `

**Comment by NimishaS** [comment] 2015-11-10 06:41
@vinyar , the new option `--azure-extension-client-config` exists in `knife-azure` `master` branch currently and is not released yet. May be that's why you faced the error. Option is defined here https://github.com/chef/knife-azure/blob/master/lib/chef/knife/azure_server_create.rb#L358

Please follow the given steps to test `master` branch:
```
$ gem uninstall 'knife-azure'
$ git clone https://github.com/chef/knife-azure
$ cd knife-azure
$ gem build knife-azure.gemspec
$ gem install ./knife-azure-1.5.0.gem    #version number may vary
```

**Comment by vinyar** [comment] 2015-11-10 20:14
oooh! I got it. I misunderstood the 'in the master branch' comment. I'll build it and retry. :+1:

**Comment by msnahill** [comment] 2015-11-13 00:26
@NimishaS,

@vinyar and I built a new Knife-Azure gem following your instructions.  After installing the gem, we added the `--azure-extension-client-config` parameter to our `knife azure server create` command and found the following:

The entire file we passed in as the value for `--azure-extension-client-config` was added to the top of the resulting `client.rb` file.  I was under the impression that this `--azure-extension-client-config` parameter would replace the `client.rb` file, not add to it.  Given your description of it's use (https://github.com/chef/knife-azure/issues/250#issuecomment-154348590), I'm not sure if the result of our test was what was intended.

Let us know whether you're happy with our result, or if you would like to make any changes to `master` and have us test again.

**Comment by vinyar** [comment] 2015-11-13 02:05
note: as part of an experiment, we created a file with just one line `ssl_verify_mode :verify_none` which  accomplished what we needed.

**Comment by NimishaS** [comment] 2015-11-13 06:32
@msnahill , @vinyar: It is an expected behavior that the extension appends some necessary parameters and handlers to the client.rb file. But that won't hamper any of the functionality.

**Comment by adamedx** [comment] 2015-11-25 06:26
Resolved with #253.

**Comment by vinyar** [comment] 2015-12-07 08:39
could we please add documentation to Readme and -h command line help

**Closed** 2015-12-07 08:39 UTC

**Comment by NimishaS** [comment] 2015-12-07 08:49
@vinyar , we'll do that

**Comment by NimishaS** [comment] 2015-12-09 11:56
@vinyar , working on updating Readme here https://github.com/chef/knife-azure/pull/270.
`-h command line help` is already updated.

**Comment by vinyar** [comment] 2015-12-12 03:16
AWSOME! Thank you!
